---
#
# Playbook to install the ELK stack + Beats
#
- hosts: elk
  roles:
  - { role: elasticsearch }
  - { role: logstash }
  - { role: kibana }


- hosts: monitored
  roles:
  - { role: metricbeat }
  

