---
# Install Metricbeat 
- name: Install Metricbeat with apt
  apt:
    name: metricbeat
    state: latest
    update_cache: yes
  when: ansible_os_family == 'Debian'


- name: Install metricbeat with yum
  yum:
    name: metricbeat
    state: latest
    update_cache: yes
  when: ansible_os_family == 'RedHat'

# Setup configuration file
- name: Setup Metricbeat configuration file
  template:
    src: metricbeat.yml.j2
    dest: /etc/metricbeat/metricbeat.yml

# Starting Metricbeat
- name: Starting Metricbeat
  service:
    name: metricbeat
    state: started
